// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinecraftCasteloConsole.Context;

#nullable disable

namespace MinecraftCasteloConsole.Migrations
{
    [DbContext(typeof(MinecraftContext))]
    partial class MinecraftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MinecraftCasteloConsole.Models.Consulta", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialUtilizado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdeConstrutores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TempoGasto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConsultaId");

                    b.ToTable("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
